import { getEnv } from '@/utils/getEnv';

export const envConfig = () => {
  const REACT_APP_SERVER_URL = getEnv('REACT_APP_SERVER_URL');
  const REACT_APP_SITE_URL = getEnv('REACT_APP_SITE_URL');
  const REACT_APP_KAKAO_JAVASCRIPT_KEY = getEnv('REACT_APP_KAKAO_JAVASCRIPT_KEY');
  const REACT_APP_GOOGLE_API_KEY = getEnv('REACT_APP_GOOGLE_API_KEY');
  const REACT_APP_BUSINESS_NUMBER_API_KEY = getEnv('REACT_APP_BUSINESS_NUMBER_API_KEY');
  const REACT_APP_IAMPORT_IMP_CODE = getEnv('REACT_APP_IAMPORT_IMP_CODE');
  return {
    REACT_APP_SERVER_URL,
    REACT_APP_SITE_URL,
    REACT_APP_KAKAO_JAVASCRIPT_KEY,
    REACT_APP_GOOGLE_API_KEY,
    REACT_APP_BUSINESS_NUMBER_API_KEY,
    REACT_APP_IAMPORT_IMP_CODE,
  };
};
